name: ROS

on:
  pull_request:
  push:
    branches: 
      - development
      - main
  workflow_dispatch:
    
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code 
        uses: actions/checkout@v3
      -
        name: Test
        uses: ./.github/actions/test/
        env:
          GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}

  complete:
    name: Tests passed
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: echo "Completed successfully!"